### ISSUE TITLE
Examples?

### ISSUE THREAD

**Issue by AndreGuerra123** [Gege7177/Dot2dot#1]
Any change we may have examples or tests?
Currently I have the following output happening:

> Processing Test length: 8001 bp
>    THREAD ID 0: No Tandem Repeats found in Test

In my FASTA I have a 36 bp direct repeat on a randomised DNA sequence as the input.

**Comment by caspargross** [comment]
Same for me. Testing on Hifi-Reads with known 3mer Repeat Expansion.

```#ID     Start   End     CN      Len     Purity  Sequence
Processing m64074_210810_142048/127273432/ccs length: 4172 bp
THREAD ID 0: No Tandem Repeats found in m64074_210810_142048/127273432/ccs
```` 

My config file looks like this:
```
FilterType=NONE
MinTRLen=15
MinMotifLen=3
MaxMotifLen=8
MaxGaps=4
MaxInsert=10
```

**Comment by Gege7177** [comment]
@caspargross @AndreGuerra123 Is it possible to you to post the sequence with unfound TR so I can debug it, please?

**Comment by Gege7177** [comment]
"No Tandem Repeats found in Test" means that the input string does not contain repeated motifs.  Try as a input a sequence like CCCCATATATATATATATATATATATATATATATATATATATATATATAGGGG
