### ISSUE TITLE
config file

### ISSUE THREAD

**Issue by dabitz** [Gege7177/Dot2dot#2]
Sorry I may have missed something, but how is supposed the config file to be like?

**Comment by Gege7177** [comment]
Dear @dabitz. An example config file is included in the repository. Dot2dot has the option -c to load it. To modify the parameters you can use the manual here (https://github.com/Gege7177/Dot2dot/blob/master/manual/dot-manual.pdf) as reference. More information in the original paper here: https://academic.oup.com/bioinformatics/article/35/6/914/5085378 Hope this helps. Thank you
