### ISSUE TITLE
Analyze Dot2dot results

### ISSUE THREAD

**Issue by awesomedeer** [Gege7177/Dot2dot#3]
Dear Dr  Filippo @Gege7177 
Thanks for developing this amazing software. I smoothly run the command.
It's by far faster than trf and I was wondering whether we can have similar summary results like trf like which tr is the most abundant.

Best regards
Song

**Comment by Gege7177** [comment]
> Dear Dr Filippo @Gege7177 Thanks for developing this amazing software. I smoothly run the command. It's by far faster than trf and I was wondering whether we can have similar summary results like trf like which tr is the most abundant.
> 
> Best regards Song

Dear Song,
can you post a sample output you may want? Do you think is it possible to post-process Dot2dot output to get what you want?
