### ISSUE TITLE
example configuration file

### ISSUE THREAD

**Issue by bw2** [Gege7177/Dot2dot#4]
It might be a good idea to copy the example configuration file to the top-level directory.
It took me a while to find it in the source code folder @ https://github.com/Gege7177/Dot2dot/blob/master/Dot-1.0.p4/configDot.cfg. 
Also, it would be nice if there were more detailed comments about the meaning of the `Substitution weights` parameters (and why commenting them out in the config file causes the tool to no longer output any repeats), Minimal Purity  (what would values 0 or 1 mean, and how does this interact with the MinMatch setting, as well as Tolerance). 
Naively playing around with these settings, the tool returns either many more repeats than I expected, or none at all.
I'm trying to find settings that would give me all 100%-pure repeats in GRCh38 chromosome 22.

**Comment by Gege7177** [comment]
The answer to most of your questions about thresholds could be find in the paper describing the algorithm (see https://academic.oup.com/bioinformatics/article/35/6/914/5085378 )
By the wey finding pure tandem repeats can be done with a naive regular expression. No nned for a tandem repeats searching tool
